project:
  type: book
  output-dir: .

book:
  title: "Elements of Sampling Survey"
  subtitle: "R Demonstrations"
  author: "Longhai Li"
  date: today
  chapters:
    - index.qmd
    - introR.qmd
    - srs.qmd
    - strata.qmd
    - ratio.qmd
    - cluster.qmd
    - ups.qmd

format:
  custombook-html: default
execute: 
  cache: true
  freeze: auto
  warning: false
  message: false
editor: source
