{
  "hash": "adf8186890b05590986c3b056d27c08d",
  "result": {
    "engine": "knitr",
    "markdown": "# Ratio, Regression, and Domain Estimation\n\n:::{.callout-note}\n\n### Key formulae\n\nWhen auxiliary information (a variable $x$) is highly correlated with our target variable of interest ($y$), we can use **Ratio** or **Regression** estimation to improve precision without increasing the sample size. We can also use auxiliary population structures to adjust our estimates after the fact via **Post-stratification**, or estimate means for specific sub-populations (**Domains**).\n\n#### 1. Ratio Estimation {-}\nIf the relationship between $y$ and $x$ passes through the origin, we estimate the ratio $B$ and use it to adjust the mean:\n\n*   **Ratio:** $\\hat{B} = \\frac{\\overline{y}}{\\overline{x}}$\n*   **Mean Estimator:** $\\overline{y}_r = \\hat{B} \\overline{x}_{\\text{U}}$ (where $\\overline{x}_{\\text{U}}$ is the true population mean of $x$)\n\n*   **Estimated Variance:** $\\hat{V}(\\overline{y}_r) = \\left(\\frac{\\overline{x}_{\\text{U}}}{\\overline{x}}\\right)^2 \\left(1 - \\frac{n}{N}\\right) \\frac{s_e^2}{n}$, where $s_e^2$ is the sample variance of the residuals $e_i = y_i - \\hat{B}x_i$.\n\n#### 2. Regression Estimation {-}\nIf the relationship does not pass through the origin, a linear regression is more appropriate:\n\n*   **Mean Estimator:** $\\overline{y}_{reg} = \\hat{B}_0 + \\hat{B}_1 \\overline{x}_{\\text{U}}$ (where $\\hat{B}_0$ and $\\hat{B}_1$ are OLS coefficients)\n*   **Estimated Variance:** $\\hat{V}(\\overline{y}_{reg}) = \\left(1 - \\frac{n}{N}\\right) \\frac{s_e^2}{n}$, where $s_e^2$ is the Mean Square Error (Residuals) from the regression.\n\n#### 3. Domain Estimation {-}\nTo estimate the mean of a subgroup (domain $d$) when the domain sample size $n_d$ is a random variable:\n\n*   **Mean Estimator:** $\\overline{y}_d = \\frac{1}{n_d} \\sum_{i \\in U_d} y_i$\n*   **Estimated Variance:** $\\hat{V}(\\overline{y}_d) = \\left(1 - \\frac{n}{N}\\right) \\frac{s_d^2}{n_d}$, where $n$ is the overall sample size, $N$ is the population size, and $s_d^2$ is the sample variance of $y$ among the $n_d$ units observed in domain $d$.\n\n#### 4. Post-stratification {-}\nIf we know the true population sizes ($N_h$) of strata, but we used a Simple Random Sample, we can post-stratify to reduce variance. We substitute $n_h$ with expected proportional sample sizes:\n\n*   $n_h^{post-strat} = n \\frac{N_h}{N}$\n\n:::\n\n## Functions and packages for Analyzing Data\n\nWe begin by loading the necessary libraries, including `gt` for formatting mathematical tables, and defining our custom functions for Ratio, Regression, Domain, and Post-stratified estimation. We also define a versatile `gt` helper to render our estimation outputs cleanly.\n\n### General functions for ratio and regression estimation\n\nThe estimating functions used throughout this book (including `reg_est`, `ratio_est`, `domain_est`, `srs_est`, and the `format_est_gt` table-formatting helper used below) live in a single shared file, `samplingestimate.r`, which we source below.\n\nFor post-stratification, we reuse the shared `str_est()` stratified estimator, but we plug in the expected sample sizes $n_h = n \\times \\frac{N_h}{N}$ instead of the actual observed random $n_h$.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-visible when-format=\"html\"}\n\n<details>\n<summary>Show the shared estimating functions (`samplingestimate.r`)</summary>\n\n```r\n# =============================================================\n# Shared estimation functions for the Elements of Sampling Survey\n# book. Source this file from any chapter that needs point/SE/CI\n# estimators or their gt-table formatting helpers, e.g.:\n#\n#   source(\"samplingestimate.r\")\n#\n# =============================================================\n\nsuppressPackageStartupMessages({\n    library(gt)\n})\n\n# ---------------------------------------------------------\n# Shared gt-table helpers\n# ---------------------------------------------------------\n\n## Formats a gt table column as ordinary fixed-point, UNLESS its values are\n## too small (< `small` in absolute value) or too large (>= `large`), in\n## which case it switches that column to scientific notation (rendered as\n## \"m x 10^n\" via gt's exp_style = \"x10n\") instead.\nfmt_auto <- function (gt_tbl, data, columns, decimals = 3, small = 1e-3, large = 1e5)\n{\n    for (col in columns)\n    {\n        x <- data[[col]]\n        x <- x[is.finite (x) & x != 0]\n        if (length (x) == 0) next\n        if (any (abs (x) < small) || any (abs (x) >= large))\n            gt_tbl <- fmt_scientific (gt_tbl, columns = tidyselect::all_of (col), decimals = decimals, exp_style = \"x10n\")\n        else\n            gt_tbl <- fmt_number (gt_tbl, columns = tidyselect::all_of (col), decimals = decimals)\n    }\n    gt_tbl\n}\n\n## Formats a single scalar for inline formula display (fixed-point with\n## thousands separators, switching to \"m \\times 10^{n}\" LaTeX scientific\n## notation for very small or very large magnitudes, mirroring fmt_auto()'s\n## use of exp_style = \"x10n\") --- used to show worked-example steps such as\n## \\bar y = sum/n with the actual numbers plugged in.\nfmt_num <- function (x, decimals = 3, small = 1e-3, large = 1e5)\n{\n    use_sci <- is.finite (x) & x != 0 & (abs (x) < small | abs (x) >= large)\n    exps    <- ifelse (x == 0, 0, floor (log10 (abs (x))))\n    mant    <- ifelse (x == 0, 0, x / 10^exps)\n    ifelse (use_sci,\n            sprintf (\"%s \\\\times 10^{%d}\", formatC (mant, format = \"f\", digits = decimals), exps),\n            formatC (x, format = \"f\", digits = decimals, big.mark = \",\"))\n}\n\n## Truncates a row-level working data.frame whose LAST row is a summary row\n## (e.g. \"Sum\"/\"Total\"): if there are more than head_n data rows (excluding\n## that summary row), keeps only the first head_n data rows, inserts one\n## \"...\" placeholder row, then the summary row --- so long working tables\n## stay readable. id_col --- name of the row-label column.\ntruncate_working <- function (working, id_col, head_n = 6)\n{\n    n <- nrow (working) - 1\n    if (n <= head_n + 1) return (working)\n\n    dots <- working[1, ]\n    dots[1, ] <- NA\n    dots[1, id_col] <- \"...\"\n\n    rbind (working[seq_len (head_n), ], dots, working[nrow (working), ])\n}\n\n# Helper function to format estimation outputs with appropriate mathematical headers\nformat_est_gt <- function(est_data, est_type = c(\"mean\", \"total\", \"ratio\", \"reg_mean\", \"reg_total\", \"ratio_mean\", \"domain_mean\")) {\n  est_type <- match.arg(est_type)\n\n  sym_map <- list(\n    \"mean\"        = c(est = \"$\\\\bar{y}$\",         se = \"$\\\\mathrm{SE}(\\\\bar{y})$\"),\n    \"total\"       = c(est = \"$\\\\hat{t}$\",         se = \"$\\\\mathrm{SE}(\\\\hat{t})$\"),\n    \"ratio\"       = c(est = \"$\\\\hat{B}$\",         se = \"$\\\\mathrm{SE}(\\\\hat{B})$\"),\n    \"reg_mean\"    = c(est = \"$\\\\bar{y}_{reg}$\",   se = \"$\\\\mathrm{SE}(\\\\bar{y}_{reg})$\"),\n    \"reg_total\"   = c(est = \"$\\\\hat{t}_{reg}$\",   se = \"$\\\\mathrm{SE}(\\\\hat{t}_{reg})$\"),\n    \"ratio_mean\"  = c(est = \"$\\\\bar{y}_{r}$\",     se = \"$\\\\mathrm{SE}(\\\\bar{y}_{r})$\"),\n    \"domain_mean\" = c(est = \"$\\\\bar{y}_{d}$\",     se = \"$\\\\mathrm{SE}(\\\\bar{y}_{d})$\")\n  )\n\n  est_sym <- sym_map[[est_type]][\"est\"]\n  se_sym  <- sym_map[[est_type]][\"se\"]\n\n  # Convert to data frame. Use unname() to strip hidden lm() coefficient names\n  if (is.vector(est_data) && !is.list(est_data)) {\n    df <- as.data.frame(t(unname(est_data)))\n  } else {\n    df <- as.data.frame(est_data)\n  }\n\n  # Force standard column names so gt() never gets confused\n  colnames(df) <- c(\"Est.\", \"S.E.\", \"ci.low\", \"ci.upp\")\n\n  # Check if we should use rownames as a stub\n  use_stub <- !is.null(rownames(df)) && !all(rownames(df) == as.character(1:nrow(df)))\n\n  df |>\n    gt(rownames_to_stub = use_stub) |>\n    cols_label(\n      Est.   = md(est_sym),\n      S.E.   = md(se_sym),\n      ci.low = md(\"95% CI Lower\"),\n      ci.upp = md(\"95% CI Upper\")\n    ) |>\n    fmt_number(\n      columns = everything(),\n      decimals = 4\n    ) |>\n    tab_options(table.width = pct(70))\n}\n\n## Formats an lm object as two gt tables, replacing the plain-text\n## summary(lmfit) output:\n##   $coef --- coefficient table (Estimate, S.E., t value, p value)\n##   $fit  --- one-row table of model fit statistics, including R^2\n## returns list($coef, $fit)\nformat_lm_gt <- function (lmfit)\n{\n    s <- summary (lmfit)\n\n    coef_df <- as.data.frame (s$coefficients)\n    colnames (coef_df) <- c (\"Estimate\", \"S.E.\", \"t value\", \"p value\")\n\n    coef_gt <- coef_df |>\n        gt (rownames_to_stub = TRUE) |>\n        fmt_number (columns = c (\"Estimate\", \"S.E.\", \"t value\"), decimals = 4) |>\n        fmt_number (columns = \"p value\", decimals = 4) |>\n        tab_header (title = \"Coefficient Estimates\") |>\n        tab_options (table.width = pct(70))\n\n    fstat <- s$fstatistic\n    fit_df <- data.frame (\n        R.squared     = s$r.squared,\n        Adj.R.squared = s$adj.r.squared,\n        Sigma         = s$sigma,\n        F.statistic   = unname (fstat[\"value\"]),\n        p.value       = unname (pf (fstat[\"value\"], fstat[\"numdf\"], fstat[\"dendf\"], lower.tail = FALSE))\n    )\n\n    fit_gt <- fit_df |>\n        gt () |>\n        cols_label (\n            R.squared     = md (\"$R^2$\"),\n            Adj.R.squared = md (\"Adj. $R^2$\"),\n            Sigma         = md (\"$\\\\hat\\\\sigma$\"),\n            F.statistic   = \"F-statistic\",\n            p.value       = \"p-value\"\n        ) |>\n        fmt_number (columns = everything (), decimals = 4) |>\n        tab_header (title = \"Model Fit Summary\") |>\n        tab_options (table.width = pct(70))\n\n    list (coef = coef_gt, fit = fit_gt)\n}\n\n# ---------------------------------------------------------\n# Base Estimators\n# ---------------------------------------------------------\n\n## sdata --- a vector of original survey data\n## N --- population size\n## estimate --- \"mean\" (default) returns the population MEAN estimate;\n##              \"total\" returns the population TOTAL estimate (N * mean,\n##              with SE/CI scaled accordingly); requires finite N\n## show.details --- if TRUE (default), also return a gt table of the\n##                  row-level working values y_i, y_i-\\bar y, (y_i-\\bar y)^2,\n##                  with a Sum row and a footnote showing s_y^2; NULL otherwise\n## returns list ($estimate = c(Est., S.E., ci.low, ci.upp), $table)\nsrs_est <- function (sdata, N = Inf, estimate = c (\"mean\", \"total\"),\n                      show.details = TRUE, col_labels = list (y = \"y_i\", ybar=\"\\\\bar y\", dev=\"e_i\"))\n{\n    estimate <- match.arg (estimate)\n\n    n <- length (sdata)\n    ybar <- mean (sdata)\n    dev <- sdata - ybar\n    s2y <- sum (dev^2) / (n - 1)\n    se.ybar <- sqrt((1 - n / N)) * sd (sdata) / sqrt(n)\n\n    if (estimate == \"total\")\n    {\n        if (!is.finite (N))\n            stop (\"N must be finite to compute estimate = \\\"total\\\"\")\n        est <- N * ybar\n        se.est <- N * se.ybar\n    }\n    else\n    {\n        est <- ybar\n        se.est <- se.ybar\n    }\n    mem <- qt (0.975, df = n - 1) * se.est\n    estimate_vec <- c (Est. = est, S.E. = se.est, ci.low = est - mem, ci.upp = est + mem)\n\n    if (!show.details)\n        return (list (estimate = estimate_vec, table = NULL))\n\n    working <- data.frame (\n        i    = c (seq_len (n), \"Sum\"),\n        y    = c (sdata, sum (sdata)),\n        ybar = rep (ybar, n + 1),\n        dev  = c (dev, sum (dev)),\n        dev2 = c (dev^2, sum (dev^2))\n    )\n    working <- truncate_working (working, id_col = \"i\")\n\n    table <- gt (working) |>\n        tab_header (title = \"SRS Mean Estimation: Working Table\", subtitle = md (sprintf (\"$n = %d$\", n))) |>\n        cols_label (\n            i    = md (\"$i$\"),\n            y    = md (sprintf (\"$%s$\", col_labels$y)),\n            ybar    = md (sprintf (\"$%s$\", col_labels$ybar)),\n            dev  = md (sprintf (\"$%s$\", col_labels$dev)),\n            dev2 = md (sprintf (\"$(%s-\\\\bar y)^2$\", col_labels$y))\n        ) |>\n        cols_width (i ~ px (40), everything () ~ px (110)) |>\n        fmt_auto (data = working, columns = c (\"y\", \"ybar\", \"dev\", \"dev2\"), decimals = 3) |>\n        sub_missing (missing_text = \"...\") |>\n        tab_style (\n            style     = cell_text (weight = \"bold\"),\n            locations = cells_body (rows = i == \"Sum\")\n        ) |>\n        tab_footnote (\n            footnote  = md (sprintf (\"$s_y^2 = \\\\sum_i (%s-\\\\bar y)^2/(n-1) = %.4f$.\", col_labels$y, s2y)),\n            locations = cells_column_labels (columns = dev2)\n        ) |>\n        tab_source_note (\n            source_note = md (if (estimate == \"total\")\n                sprintf (\"$\\\\hat t = N\\\\bar y = %s \\\\times %s = %s$\",\n                         fmt_num (N, 0), fmt_num (ybar), fmt_num (est))\n            else\n                sprintf (\"$\\\\bar y = \\\\dfrac{\\\\sum_i %s}{n} = \\\\dfrac{%s}{%d} = %s$\",\n                         col_labels$y, fmt_num (sum (sdata)), n, fmt_num (ybar)))\n        ) |>\n        tab_source_note (\n            source_note = md (if (estimate == \"total\")\n                sprintf (\"$\\\\mathrm{SE}(\\\\hat t) = N \\\\times \\\\mathrm{SE}(\\\\bar y) = %s \\\\times %s = %s$\",\n                         fmt_num (N, 0), fmt_num (se.ybar), fmt_num (se.est))\n            else if (is.finite (N))\n                sprintf (\"$\\\\mathrm{SE}(\\\\bar y) = \\\\sqrt{1-\\\\dfrac{n}{N}}\\\\,\\\\dfrac{s}{\\\\sqrt n} = \\\\sqrt{1-\\\\dfrac{%d}{%d}}\\\\,\\\\dfrac{%s}{\\\\sqrt{%d}} = %s$\",\n                         n, N, fmt_num (sqrt (s2y)), n, fmt_num (se.ybar))\n            else\n                sprintf (\"$\\\\mathrm{SE}(\\\\bar y) = \\\\dfrac{s}{\\\\sqrt n} = \\\\dfrac{%s}{\\\\sqrt{%d}} = %s$\",\n                         fmt_num (sqrt (s2y)), n, fmt_num (se.ybar)))\n        )\n\n    list (estimate = estimate_vec, table = table)\n}\n\n## ydata --- observations of the variable of interest\n## xdata --- observations of the auxiliary variable\n## xbarU --- population mean of the auxiliary variable; required when\n##           estimate is \"mean\" or \"total\"; ignored when estimate = \"model\"\n## N --- population size\n## estimate --- \"mean\" (default) returns the ratio estimate of the\n##              population MEAN of y, Bhat*xbarU; \"total\" returns the ratio\n##              estimate of the population TOTAL of y (requires finite N);\n##              \"model\" returns the raw ratio coefficient Bhat = ybar/xbar\n##              itself (with its own SE)\n## show.details --- if TRUE (default), also return a gt table of the\n##                  row-level working values y_i, x_i, fitted yhat_i =\n##                  Bhat*x_i, residual e_i, and e_i^2, with a Sum row and a\n##                  footnote showing Bhat and s_e^2; NULL otherwise\n## col_labels --- named list (y, x, yhat) of RAW latex for those\n##                working-table columns, so this function can be reused\n##                (e.g. by cluster_ratio(), upswr_ratio()) with\n##                context-appropriate labels\n## extra_col --- optional list (label, values, formula) adding one extra\n##               RAW-latex-labelled column of per-unit `values` right before\n##               the y column of the working table (e.g. the within-cluster\n##               means $\\bar y_i$ used by cluster_ratio() to build $\\hat\n##               t_i = \\bar y_i M_i$); `formula` (optional) is shown as a\n##               footnote on the y column documenting that relationship\n## returns list ($estimate = c(Est., S.E., ci.low, ci.upp), $table)\nratio_est <- function (ydata, xdata, xbarU = NULL, N = Inf,\n                        estimate = c (\"mean\", \"total\", \"model\"), show.details = TRUE,\n                        col_labels = list (y = \"y_i\", x = \"x_i\", yhat = \"\\\\hat y_i\"),\n                        extra_col = NULL)\n{\n  estimate <- match.arg (estimate)\n\n  n <- length (xdata)\n  xbar <- mean (xdata)\n  ybar <- mean (ydata)\n  B_hat <- ybar / xbar\n  yhat <- B_hat * xdata\n  e <- ydata - yhat\n  var_e <- sum (e^2) / (n - 1)\n  sd_B_hat <- sqrt ((1 - n/N) * var_e / n) / xbar\n\n  if (estimate == \"model\")\n  {\n      est <- B_hat\n      sd_est <- sd_B_hat\n  }\n  else\n  {\n      if (is.null (xbarU))\n          stop (\"xbarU (population mean of x) is required when estimate is \\\"mean\\\" or \\\"total\\\"\")\n      if (estimate == \"total\")\n      {\n          if (!is.finite (N))\n              stop (\"N must be finite to compute estimate = \\\"total\\\"\")\n          est <- B_hat * xbarU * N\n          sd_est <- sd_B_hat * xbarU * N\n      }\n      else\n      {\n          est <- B_hat * xbarU\n          sd_est <- sd_B_hat * xbarU\n      }\n  }\n\n  mem <- qt (0.975, df = n - 1) * sd_est\n  estimate_vec <- c (Est. = est, S.E. = sd_est, ci.low = est - mem, ci.upp = est + mem)\n\n  if (!show.details)\n      return (list (estimate = estimate_vec, table = NULL))\n\n  working_cols <- list (i = c (seq_len (n), \"Sum\"))\n  if (!is.null (extra_col))\n      working_cols$extra <- c (extra_col$values, NA)\n  working_cols$y    <- c (ydata, sum (ydata))\n  working_cols$x    <- c (xdata, sum (xdata))\n  working_cols$yhat <- c (yhat, sum (yhat))\n  working_cols$e    <- c (e, sum (e))\n  working_cols$e2   <- c (e^2, sum (e^2))\n  working <- as.data.frame (working_cols, check.names = FALSE)\n  working <- truncate_working (working, id_col = \"i\")\n\n  fmt_cols <- c (\"y\", \"x\", \"yhat\", \"e\", \"e2\")\n  if (!is.null (extra_col)) fmt_cols <- c (\"extra\", fmt_cols)\n\n  label_args <- list (i = md (\"$i$\"))\n  if (!is.null (extra_col))\n      label_args$extra <- md (sprintf (\"$%s$\", extra_col$label))\n  label_args$y    <- md (sprintf (\"$%s$\", col_labels$y))\n  label_args$x    <- md (sprintf (\"$%s$\", col_labels$x))\n  label_args$yhat <- md (sprintf (\"$%s$\", col_labels$yhat))\n  label_args$e    <- md (\"$e_i$\")\n  label_args$e2   <- md (\"$e_i^2$\")\n\n  table <- gt (working) |>\n      tab_header (title = \"Ratio Estimation: Working Table\", subtitle = md (sprintf (\"$n = %d$\", n)))\n  table <- do.call (cols_label, c (list (table), label_args))\n  table <- table |>\n      cols_width (i ~ px (40), everything () ~ px (100)) |>\n      fmt_auto (data = working, columns = fmt_cols, decimals = 3) |>\n      sub_missing (missing_text = \"...\") |>\n      tab_style (\n          style     = cell_text (weight = \"bold\"),\n          locations = cells_body (rows = i == \"Sum\")\n      ) |>\n      tab_footnote (\n          footnote  = md (sprintf (\"$\\\\hat B = \\\\sum_i %s / \\\\sum_i %s = %.4f$, $%s = \\\\hat B\\\\, %s$, $s_e^2 = %.4f$.\",\n                                    col_labels$y, col_labels$x, B_hat, col_labels$yhat, col_labels$x, var_e)),\n          locations = cells_column_labels (columns = yhat)\n      )\n  if (!is.null (extra_col) && !is.null (extra_col$formula))\n      table <- table |>\n          tab_footnote (\n              footnote  = md (sprintf (\"$%s$.\", extra_col$formula)),\n              locations = cells_column_labels (columns = y)\n          )\n  table <- table |>\n      tab_source_note (\n          source_note = md (if (estimate == \"model\")\n              sprintf (\"$\\\\hat B = \\\\dfrac{\\\\sum_i %s}{\\\\sum_i %s} = \\\\dfrac{%s}{%s} = %s$\",\n                       col_labels$y, col_labels$x, fmt_num (sum (ydata)), fmt_num (sum (xdata)), fmt_num (B_hat))\n          else if (estimate == \"total\")\n              sprintf (\"$\\\\hat t = \\\\hat B\\\\,\\\\bar x_U\\\\,N = %s \\\\times %s \\\\times %s = %s$\",\n                       fmt_num (B_hat), fmt_num (xbarU), fmt_num (N, 0), fmt_num (est))\n          else\n              sprintf (\"$\\\\bar y_r = \\\\hat B\\\\,\\\\bar x_U = %s \\\\times %s = %s$\",\n                       fmt_num (B_hat), fmt_num (xbarU), fmt_num (est)))\n      ) |>\n      tab_source_note (\n          source_note = md (if (estimate == \"model\")\n              (if (is.finite (N))\n                  sprintf (\"$\\\\mathrm{SE}(\\\\hat B) = \\\\dfrac{1}{\\\\bar x}\\\\sqrt{\\\\left(1-\\\\dfrac{n}{N}\\\\right)\\\\dfrac{s_e^2}{n}} = \\\\dfrac{1}{%s}\\\\sqrt{\\\\left(1-\\\\dfrac{%d}{%d}\\\\right)\\\\dfrac{%s}{%d}} = %s$\",\n                          fmt_num (xbar), n, N, fmt_num (var_e), n, fmt_num (sd_B_hat))\n              else\n                  sprintf (\"$\\\\mathrm{SE}(\\\\hat B) = \\\\dfrac{1}{\\\\bar x}\\\\sqrt{\\\\dfrac{s_e^2}{n}} = \\\\dfrac{1}{%s}\\\\sqrt{\\\\dfrac{%s}{%d}} = %s$\",\n                          fmt_num (xbar), fmt_num (var_e), n, fmt_num (sd_B_hat)))\n          else if (estimate == \"total\")\n              sprintf (\"$\\\\mathrm{SE}(\\\\hat t) = \\\\mathrm{SE}(\\\\hat B)\\\\,\\\\bar x_U\\\\,N = %s \\\\times %s \\\\times %s = %s$\",\n                       fmt_num (sd_B_hat), fmt_num (xbarU), fmt_num (N, 0), fmt_num (sd_est))\n          else\n              sprintf (\"$\\\\mathrm{SE}(\\\\bar y_r) = \\\\mathrm{SE}(\\\\hat B)\\\\,\\\\bar x_U = %s \\\\times %s = %s$\",\n                       fmt_num (sd_B_hat), fmt_num (xbarU), fmt_num (sd_est)))\n      )\n\n  list (estimate = estimate_vec, table = table)\n}\n\n## ydata --- observations of the variable of interest\n## xdata --- observations of the auxiliary variable\n## xbarU --- population mean of the auxiliary variable; required when\n##           estimate is \"mean\" or \"total\"; ignored when estimate = \"model\"\n## N --- population size\n## estimate --- \"mean\" (default) returns the regression estimate of the\n##              population MEAN of y, Bhat0 + Bhat1*xbarU; \"total\" returns\n##              the regression estimate of the population TOTAL of y\n##              (requires finite N); \"model\" returns the raw fitted slope\n##              Bhat1 itself (with its own SE from the lm fit)\n## show.details --- if TRUE (default), also return a gt table of the\n##                  row-level working values y_i, x_i, fitted yhat_i, e_i,\n##                  e_i^2, with a Sum row and a footnote showing Bhat0,\n##                  Bhat1, and s_e^2; NULL otherwise\n## returns list ($estimate = c(Est., S.E., ci.low, ci.upp), $table)\nreg_est <- function (ydata, xdata, xbarU = NULL, N = Inf,\n                      estimate = c (\"mean\", \"total\", \"model\"), show.details = TRUE)\n{\n  estimate <- match.arg (estimate)\n\n  n <- length (ydata)\n  lmfit <- lm (ydata ~ xdata)\n  Bhat <- lmfit$coefficients\n  yhat <- lmfit$fitted.values\n  e <- lmfit$residuals\n  SSe <- sum (e^2) / (n - 2)\n\n  if (estimate == \"model\")\n  {\n      est <- unname (Bhat[2])\n      sd_est <- summary (lmfit)$coefficients[2, \"Std. Error\"]\n  }\n  else\n  {\n      if (is.null (xbarU))\n          stop (\"xbarU (population mean of x) is required when estimate is \\\"mean\\\" or \\\"total\\\"\")\n      yhat_reg <- unname (Bhat[1] + Bhat[2] * xbarU)\n      se_yhat_reg <- sqrt ((1-n/N) * SSe / n)\n      if (estimate == \"total\")\n      {\n          if (!is.finite (N))\n              stop (\"N must be finite to compute estimate = \\\"total\\\"\")\n          est <- yhat_reg * N\n          sd_est <- se_yhat_reg * N\n      }\n      else\n      {\n          est <- yhat_reg\n          sd_est <- se_yhat_reg\n      }\n  }\n\n  mem <- qt (0.975, df = n - 2) * sd_est\n  estimate_vec <- c (Est. = est, S.E. = sd_est, ci.low = est - mem, ci.upp = est + mem)\n\n  if (!show.details)\n      return (list (estimate = estimate_vec, table = NULL))\n\n  Sxx <- sum ((xdata - mean (xdata))^2)\n  Sxy <- sum ((xdata - mean (xdata)) * (ydata - mean (ydata)))\n\n  working <- data.frame (\n      i    = c (seq_len (n), \"Sum\"),\n      y    = c (ydata, sum (ydata)),\n      x    = c (xdata, sum (xdata)),\n      yhat = c (yhat, sum (yhat)),\n      e    = c (e, sum (e)),\n      e2   = c (e^2, sum (e^2))\n  )\n  working <- truncate_working (working, id_col = \"i\")\n\n  table <- gt (working) |>\n      tab_header (title = \"Regression Estimation: Working Table\", subtitle = md (sprintf (\"$n = %d$\", n))) |>\n      cols_label (\n          i    = md (\"$i$\"),\n          y    = md (\"$y_i$\"),\n          x    = md (\"$x_i$\"),\n          yhat = md (\"$\\\\hat y_i$\"),\n          e    = md (\"$e_i$\"),\n          e2   = md (\"$e_i^2$\")\n      ) |>\n      cols_width (i ~ px (40), everything () ~ px (100)) |>\n      fmt_auto (data = working, columns = c (\"y\", \"x\", \"yhat\", \"e\", \"e2\"), decimals = 3) |>\n      sub_missing (missing_text = \"...\") |>\n      tab_style (\n          style     = cell_text (weight = \"bold\"),\n          locations = cells_body (rows = i == \"Sum\")\n      ) |>\n      tab_footnote (\n          footnote  = md (sprintf (\"$\\\\hat B_0 = %.4f$, $\\\\hat B_1 = %.4f$, $\\\\hat y_i = \\\\hat B_0 + \\\\hat B_1 x_i$, $s_e^2 = %.4f$.\",\n                                    Bhat[1], Bhat[2], SSe)),\n          locations = cells_column_labels (columns = yhat)\n      ) |>\n      tab_source_note (\n          source_note = md (if (estimate == \"model\")\n              sprintf (\"$\\\\hat B_1 = \\\\dfrac{\\\\sum_i(x_i-\\\\bar x)(y_i-\\\\bar y)}{\\\\sum_i(x_i-\\\\bar x)^2} = \\\\dfrac{%s}{%s} = %s$\",\n                       fmt_num (Sxy), fmt_num (Sxx), fmt_num (unname (Bhat[2])))\n          else if (estimate == \"total\")\n              sprintf (\"$\\\\hat t_{reg} = N\\\\bar y_{reg} = %s \\\\times %s = %s$\",\n                       fmt_num (N, 0), fmt_num (yhat_reg), fmt_num (est))\n          else\n              sprintf (\"$\\\\bar y_{reg} = \\\\hat B_0+\\\\hat B_1\\\\bar x_U = %s + %s \\\\times %s = %s$\",\n                       fmt_num (Bhat[1]), fmt_num (Bhat[2]), fmt_num (xbarU), fmt_num (yhat_reg)))\n      ) |>\n      tab_source_note (\n          source_note = md (if (estimate == \"model\")\n              sprintf (\"$\\\\mathrm{SE}(\\\\hat B_1) = \\\\sqrt{\\\\dfrac{s_e^2}{\\\\sum_i(x_i-\\\\bar x)^2}} = \\\\sqrt{\\\\dfrac{%s}{%s}} = %s$\",\n                       fmt_num (SSe), fmt_num (Sxx), fmt_num (sd_est))\n          else if (estimate == \"total\")\n              sprintf (\"$\\\\mathrm{SE}(\\\\hat t_{reg}) = N\\\\times\\\\mathrm{SE}(\\\\bar y_{reg}) = %s \\\\times %s = %s$\",\n                       fmt_num (N, 0), fmt_num (se_yhat_reg), fmt_num (sd_est))\n          else if (is.finite (N))\n              sprintf (\"$\\\\mathrm{SE}(\\\\bar y_{reg}) = \\\\sqrt{\\\\left(1-\\\\dfrac{n}{N}\\\\right)\\\\dfrac{s_e^2}{n}} = \\\\sqrt{\\\\left(1-\\\\dfrac{%d}{%d}\\\\right)\\\\dfrac{%s}{%d}} = %s$\",\n                       n, N, fmt_num (SSe), n, fmt_num (se_yhat_reg))\n          else\n              sprintf (\"$\\\\mathrm{SE}(\\\\bar y_{reg}) = \\\\sqrt{\\\\dfrac{s_e^2}{n}} = \\\\sqrt{\\\\dfrac{%s}{%d}} = %s$\",\n                       fmt_num (SSe), n, fmt_num (se_yhat_reg)))\n      )\n\n  list (estimate = estimate_vec, table = table)\n}\n\n## sdata --- a vector of original survey data in a domain\n## N --- population size\n## n --- total sample size (not the sample size in the domain)\n## to find total, multiply domain size N_d to the estimate returned by this function\ndomain_est <- function (sdata, n, N = Inf)\n{\n    n_d <- length (sdata)\n    ybar <- mean (sdata)\n    se.ybar <- sqrt((1 - n / N)) * sd (sdata) / sqrt(n_d)\n    mem <- qt (0.975, df = n_d - 1) * se.ybar\n    c (Est. = ybar, S.E. = se.ybar, ci.low = ybar - mem, ci.upp = ybar + mem)\n}\n\n# ---------------------------------------------------------\n# Stratified Estimator\n# ---------------------------------------------------------\n\n## Given per-stratum summaries, compute the stratified (or post-stratified)\n## mean or total.\n## estimate --- \"mean\" (default) returns the stratified MEAN estimate;\n##              \"total\" returns the stratified TOTAL estimate\n## show.details --- if TRUE (default), also return a gt table showing the\n##                  stratum-by-stratum working, with a Total row\n## for poststratification, use nh = n * Nh/N\n## returns list ($estimate = c(Est., S.E., ci.low, ci.upp), $table)\nstr_est <- function (ybarh, sh, nh, Nh, estimate = c (\"mean\", \"total\"), show.details = TRUE)\n{\n    estimate <- match.arg (estimate)\n\n    N    <- sum (Nh)\n    Pi_h <- Nh / N\n    v_h  <- (1 - nh / Nh) * Pi_h^2 * sh^2 / nh\n\n    ybar   <- sum (ybarh * Pi_h)\n    seybar <- sqrt (sum (v_h))\n\n    if (estimate == \"total\")\n    {\n        est    <- N * ybar\n        se.est <- N * seybar\n    }\n    else\n    {\n        est    <- ybar\n        se.est <- seybar\n    }\n    mem          <- 1.96 * se.est\n    estimate_vec <- c (Est. = est, S.E. = se.est, ci.low = est - mem, ci.upp = est + mem)\n\n    if (!show.details)\n        return (list (estimate = estimate_vec, table = NULL))\n\n    stratum <- names (Nh)\n    if (is.null (stratum)) stratum <- seq_along (Nh)\n\n    working <- data.frame (\n        Stratum       = c (stratum, \"Total\"),\n        Nh            = c (Nh, N),\n        nh            = c (nh, sum (nh)),\n        Pi_h          = c (Pi_h, sum (Pi_h)),\n        ybarh         = c (ybarh, NA),\n        sh2           = c (sh^2, NA),\n        weighted_mean = c (Pi_h * ybarh, ybar),\n        v_h           = c (v_h, seybar^2)\n    )\n\n    table <- gt (working) |>\n        tab_header (title = \"Stratified Mean Estimation: Working Table\") |>\n        cols_label (\n            Stratum       = md (\"Stratum\"),\n            Nh            = md (\"$N_h$\"),\n            nh            = md (\"$n_h$\"),\n            Pi_h          = md (\"$\\\\pi_h$\"),\n            ybarh         = md (\"$\\\\bar y_h$\"),\n            sh2           = md (\"$s_h^2$\"),\n            weighted_mean = md (\"$\\\\pi_h\\\\bar y_h$\"),\n            v_h           = md (\"$v_h$\")\n        ) |>\n        cols_width (c (Nh, nh) ~ px (60), everything () ~ px (110)) |>\n        fmt_number (columns = c (Nh, nh), decimals = 0) |>\n        fmt_number (columns = Pi_h, decimals = 2) |>\n        fmt_auto (data = working, columns = c (\"ybarh\", \"sh2\", \"weighted_mean\", \"v_h\"), decimals = 2) |>\n        sub_missing (missing_text = \"\") |>\n        tab_style (\n            style     = cell_text (weight = \"bold\"),\n            locations = cells_body (rows = Stratum == \"Total\")\n        ) |>\n        tab_footnote (\n            footnote  = md (\"$\\\\pi_h = N_h/N$ is the stratum weight.\"),\n            locations = cells_column_labels (columns = Pi_h)\n        ) |>\n        tab_footnote (\n            footnote  = md (\"$v_h = (1-n_h/N_h)\\\\,\\\\pi_h^2\\\\, s_h^2/n_h$ is stratum $h$'s contribution to $V(\\\\bar y_{str}) = \\\\sum_h v_h$.\"),\n            locations = cells_column_labels (columns = v_h)\n        ) |>\n        tab_source_note (\n            source_note = md (if (estimate == \"total\")\n                sprintf (\"$\\\\hat t_{str} = N\\\\bar y_{str} = %s \\\\times %s = %s$\",\n                         fmt_num (N, 0), fmt_num (ybar), fmt_num (est))\n            else\n                sprintf (\"$\\\\bar y_{str} = \\\\sum_h \\\\pi_h\\\\bar y_h = %s$\", fmt_num (ybar)))\n        ) |>\n        tab_source_note (\n            source_note = md (if (estimate == \"total\")\n                sprintf (\"$\\\\mathrm{SE}(\\\\hat t_{str}) = N \\\\times \\\\mathrm{SE}(\\\\bar y_{str}) = %s \\\\times %s = %s$\",\n                         fmt_num (N, 0), fmt_num (seybar), fmt_num (se.est))\n            else\n                sprintf (\"$\\\\mathrm{SE}(\\\\bar y_{str}) = \\\\sqrt{\\\\sum_h v_h} = \\\\sqrt{%s} = %s$\",\n                         fmt_num (sum (v_h)), fmt_num (seybar)))\n        )\n\n    list (estimate = estimate_vec, table = table)\n}\n\n## this function finds statistical estimates given a dataset with sampling weight\n# stratdata --- data.frame containing stratified sample\n# y --- name of variable for which we want to estiamte population mean\n# stratum --- name of variable that will be used as stratum variable\n# weight --- name of variable indicating sampling weight\n# note: from weights we can find Nh (see the code for formula)\n# returns the same list ($estimate, $table) as str_est(), which\n# this function calls after deriving ybarh/sh/nh/Nh from the raw data\nstr_est_data <- function (stratdata, y, stratum, weight, estimate = c (\"mean\", \"total\"), show.details = TRUE)\n{\n    ## compute stratum-wise data\n    sh <- tapply (stratdata[, y], stratdata[,stratum], sd)\n    ybarh <- tapply (stratdata[, y], stratdata[,stratum], mean)\n    ## find population stratum size using sampling weight included in the data set\n    Nh <- tapply (stratdata[, weight], stratdata[,stratum], sum)\n    nh <- tapply (1:nrow(stratdata), stratdata[,stratum], length)\n\n    str_est (ybarh, sh, nh, Nh, estimate = estimate, show.details = show.details)\n}\n\n# ---------------------------------------------------------\n# Cluster (ratio-to-size) Estimator\n# ---------------------------------------------------------\n\n## Cluster ratio estimation (one-stage if Mi = mi, i.e. every element in the\n## sampled cluster is measured; two-stage/ratio-to-size if only mi < Mi\n## elements are subsampled, so t_hat_i = Mi * ybari is an ESTIMATED total).\n## data --- original data frame for holding data\n## cname --- variable recording cluster (psu) identity\n## csize --- variable recording cluster (psu) population size (not sample size)\n## yvar --- variable of interest\n## N --- total number of clusters (psus) in the population\n## estimate --- \"mean\" (default) or \"model\" both return the raw ratio\n##              Bhat = sum(t_hat_i)/sum(Mi) --- for this ratio-to-size\n##              cluster estimator, that raw B IS the population MEAN per\n##              element, so the two coincide; \"total\" returns the\n##              population TOTAL of y, Bhat*Mtotal_U (requires Mtotal_U,\n##              the population total of the cluster-size variable)\n## Mtotal_U --- population total of the cluster-size variable; required\n##              when estimate = \"total\"\n## show.details --- if TRUE, also return a gt table of the cluster-level\n##                  working values (t_hat_i, M_i, fitted, e_i, e_i^2), via\n##                  ratio_est()'s own working table\n## returns list ($estimate = c(Est., S.E., ci.low, ci.upp), $table)\ncluster_ratio <- function (data, cname, csize, yvar, N = Inf,\n                            estimate = c (\"mean\", \"total\", \"model\"),\n                            show.details = TRUE, Mtotal_U = NULL)\n{\n  estimate <- match.arg (estimate)\n\n  clust <- data[, cname]\n  ydata <- data[, yvar]\n\n  ybari <- tapply (ydata, clust, mean)\n  Mi    <- tapply (data[, csize], clust, function (x) x[1])\n  ## same as the cluster total if all Mi elements were measured (mi = Mi)\n  t_hat_cls <- ybari * Mi\n\n  ybar_col <- list (label = \"\\\\bar y_i\", values = ybari, formula = \"\\\\hat t_i = \\\\bar y_i \\\\, M_i\")\n\n  if (estimate == \"total\")\n  {\n      if (is.null (Mtotal_U))\n          stop (\"Mtotal_U (population total of the cluster-size variable) is required when estimate = \\\"total\\\"\")\n      ratio_est (t_hat_cls, Mi, xbarU = Mtotal_U, N = N, estimate = \"mean\", show.details = show.details,\n                 col_labels = list (y = \"\\\\hat t_i\", x = \"M_i\", yhat = \"\\\\hat B M_i\"),\n                 extra_col = ybar_col)\n  }\n  else\n  {\n      ratio_est (t_hat_cls, Mi, N = N, estimate = \"model\", show.details = show.details,\n                 col_labels = list (y = \"\\\\hat t_i\", x = \"M_i\", yhat = \"\\\\hat B M_i\"),\n                 extra_col = ybar_col)\n  }\n}\n\n# ---------------------------------------------------------\n# UPS Estimators\n# ---------------------------------------------------------\n\n## Total estimation for datasets collected with UPS with Replacement\n## (psi-estimator / Hansen-Hurwitz).\n## estimate --- \"total\" (default) is this function's whole purpose, computed\n##              as the SAMPLE MEAN of the expanded pseudo-values t_i/psi_i\n##              (a with-replacement HT-type property); \"mean\" instead\n##              divides that total by N (requires finite N)\nupswr_total <- function (total, psi, N = Inf, estimate = c (\"total\", \"mean\"), show.details = TRUE)\n{\n  estimate <- match.arg (estimate)\n  res <- srs_est (total/psi, N = N, estimate = \"mean\", show.details = show.details,\n                  col_labels = list (y = \"t_i/\\\\psi_i\"))\n  if (estimate == \"mean\")\n  {\n      if (!is.finite (N)) stop (\"N must be finite to compute estimate = \\\"mean\\\" (mean total per psu)\")\n      res$estimate <- res$estimate / N\n  }\n  res\n}\n\n## Ratio estimation for datasets collected with UPS with Replacement.\n## estimate --- \"mean\" (default) or \"model\" both return the raw ratio\n##              Bhat = sum(t_i/psi_i)/sum(M_i/psi_i) --- that raw B IS the\n##              population MEAN per element; \"total\" returns the population\n##              TOTAL of y, Bhat*Mtotal_U (requires Mtotal_U, the population\n##              total of the size variable)\nupswr_ratio <- function (total, M, psi, N = Inf, estimate = c (\"mean\", \"total\", \"model\"),\n                          show.details = TRUE, Mtotal_U = NULL)\n{\n  estimate <- match.arg (estimate)\n\n  if (estimate == \"total\")\n  {\n      if (is.null (Mtotal_U))\n          stop (\"Mtotal_U (population total of the size variable) is required when estimate = \\\"total\\\"\")\n      ratio_est (total/psi, M/psi, xbarU = Mtotal_U, N = N, estimate = \"mean\", show.details = show.details,\n                 col_labels = list (y = \"t_i/\\\\psi_i\", x = \"M_i/\\\\psi_i\", yhat = \"\\\\hat B\\\\,M_i/\\\\psi_i\"))\n  }\n  else\n  {\n      ratio_est (total/psi, M/psi, N = N, estimate = \"model\", show.details = show.details,\n                 col_labels = list (y = \"t_i/\\\\psi_i\", x = \"M_i/\\\\psi_i\", yhat = \"\\\\hat B\\\\,M_i/\\\\psi_i\"))\n  }\n}\n\n## Cluster UPS with Replacement: aggregates to the cluster level (ybari, Mi,\n## psi per sampled cluster), then delegates to upswr_ratio(), so the\n## working table and estimate/total logic are shared with the base function.\n## data --- data frame holding the sample\n## sid --- variable recording cluster (psu) identity\n## csize --- variable recording cluster (psu) population size\n## cpsi --- variable recording the cluster's selection probability psi_i\n## yvar --- variable of interest (element level)\n## estimate, Mtotal_U --- see upswr_ratio()\ncluster_upswr_ratio <- function (data, sid, csize, cpsi, yvar, N = Inf,\n                                  estimate = c (\"mean\", \"total\", \"model\"),\n                                  show.details = TRUE, Mtotal_U = NULL)\n{\n    estimate <- match.arg (estimate)\n\n    clust <- data[, sid]\n    ydata <- data[, yvar]\n\n    ybari <- tapply (ydata, clust, mean)\n    Mi <- tapply (data[,csize], clust, function (x) x[1])\n    psi <- tapply (data[,cpsi], clust, function (x) x[1])\n    t_hat_cls <- ybari * Mi\n\n    upswr_ratio (t_hat_cls, Mi, psi, N = N, estimate = estimate,\n                 show.details = show.details, Mtotal_U = Mtotal_U)\n}\n\n## Cluster UPS without Replacement: same idea as cluster_upswr_ratio(),\n## but dividing by the cluster's inclusion probability pik instead of psi.\n## data --- data frame holding the sample\n## cname --- variable recording cluster identity\n## csize --- variable recording cluster population size\n## cpik --- variable recording the cluster's inclusion probability pi_k\n## yvar --- variable of interest (element level)\ncluster_upswo_ratio <- function (data, cname, csize, cpik, yvar, N = Inf,\n                                  estimate = c (\"mean\", \"total\", \"model\"),\n                                  show.details = TRUE, Mtotal_U = NULL)\n{\n  estimate <- match.arg (estimate)\n\n  clust <- data[, cname]\n  ydata <- data[, yvar]\n\n  ybari <- tapply (ydata, clust, mean)\n  Mi <- tapply (data[,csize], clust, function (x) x[1])\n  pik <- tapply (data[,cpik], clust, function (x) x[1])\n  t_hat_cls <- ybari * Mi\n\n  if (estimate == \"total\")\n  {\n      if (is.null (Mtotal_U))\n          stop (\"Mtotal_U (population total of the size variable) is required when estimate = \\\"total\\\"\")\n      ratio_est (t_hat_cls/pik, Mi/pik, xbarU = Mtotal_U, N = N, estimate = \"mean\", show.details = show.details,\n                 col_labels = list (y = \"\\\\hat t_i/\\\\pi_i\", x = \"M_i/\\\\pi_i\", yhat = \"\\\\hat B\\\\,M_i/\\\\pi_i\"))\n  }\n  else\n  {\n      ratio_est (t_hat_cls/pik, Mi/pik, N = N, estimate = \"model\", show.details = show.details,\n                 col_labels = list (y = \"\\\\hat t_i/\\\\pi_i\", x = \"M_i/\\\\pi_i\", yhat = \"\\\\hat B\\\\,M_i/\\\\pi_i\"))\n  }\n}\n\n```\n\n</details>\n\n:::\n\n\n## Ratio Estimation for cherry.csv dataset \n\nWe want to estimate the volume of wood in cherry trees using their diameter as an auxiliary variable. \n\n### Importing data\n\nFirst, let's load the data and verify that a strong linear relationship passing near the origin exists between volume and diameter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncherry <- read.csv(\"data/cherry.csv\", header = T)\nhead(cherry) |> gt()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rrr}\n\\toprule\ndiameter & height & volume \\\\ \n\\midrule\\addlinespace[2.5pt]\n8.3 & 70 & 10.3 \\\\ \n8.6 & 65 & 10.3 \\\\ \n8.8 & 63 & 10.2 \\\\ \n10.5 & 72 & 16.4 \\\\ \n10.7 & 81 & 18.8 \\\\ \n10.8 & 83 & 19.7 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nplot(cherry$volume ~ cherry$diameter, main = \"Volume vs Diameter\")\n```\n\n::: {.cell-output-display}\n![](ratio_files/figure-pdf/cherry-load-plot-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nanova(lm(cherry$volume ~ 0 + cherry$diameter))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: cherry$volume\n                Df Sum Sq Mean Sq F value    Pr(>F)    \ncherry$diameter  1  33622   33622  373.12 < 2.2e-16 ***\nResiduals       30   2703      90                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n**Output Note:** The plot and the linear model output (which forces a 0 intercept) confirm a very strong relationship, making this a prime candidate for Ratio estimation.\n\n### SRS estimate \n\nTo establish a baseline, we first estimate the mean and total volume using standard Simple Random Sampling (ignoring the auxiliary variable).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- 2967\n## estimating the mean of volume\nres_srs_vol <- srs_est(cherry$volume, N = N, estimate = \"mean\", show.details = FALSE)\nsrs_mean_vol_raw <- res_srs_vol$estimate\nsrs_mean_vol_raw |> format_est_gt(\"mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\bar{y}\\) & \\(\\mathrm{SE}(\\bar{y})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n30.1710 & 2.9369 & 24.1731 & 36.1688 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\n## estimating the total of volume\nres_srs_total_vol <- srs_est(cherry$volume, N = N, estimate = \"total\", show.details = FALSE)\nsrs_total_vol_raw <- res_srs_total_vol$estimate\nsrs_total_vol_raw |> format_est_gt(\"total\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\hat{t}\\) & \\(\\mathrm{SE}(\\hat{t})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n89,517.2613 & 8,713.6652 & 71,721.5828 & 107,312.9398 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n**Output Note:** Under SRS, the standard error for the mean volume is 2.94.\n\n### Ratio Estimation Using the Function\n\nWe calculate the ratio $\\hat{B} = \\overline{y}/\\overline{x}$; the function's `$table` shows the row-level working values $x_i$, $y_i$, fitted $\\hat{y}_i = \\hat{B}x_i$, residuals $e_i = y_i - \\hat{y}_i$, and $e_i^2$ (with a Sum row and a footnote giving $\\hat B$ and $s_e^2$), so we no longer need to build this table by hand.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nydata <- cherry$volume\nxdata <- cherry$diameter\nN <- 2967\n\nres_ratio_model <- ratio_est(ydata, xdata, N = N, estimate = \"model\")\nres_ratio_model$table\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Ratio Estimation: Working Table\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  \\(n = 31\\)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}p{\\dimexpr 30.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}}\n\\toprule\n\\(i\\) & \\(y_i\\) & \\(x_i\\) & \\(\\hat y_i\\)\\textsuperscript{\\textit{1}} & \\(e_i\\) & \\(e_i^2\\) \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 10.300 & 8.300 & 18.902 & -8.602 & 73.992 \\\\ \n2 & 10.300 & 8.600 & 19.585 & -9.285 & 86.212 \\\\ \n3 & 10.200 & 8.800 & 20.041 & -9.841 & 96.836 \\\\ \n4 & 16.400 & 10.500 & 23.912 & -7.512 & 56.430 \\\\ \n5 & 18.800 & 10.700 & 24.367 & -5.567 & 30.996 \\\\ \n6 & 19.700 & 10.800 & 24.595 & -4.895 & 23.963 \\\\ \n... & ... & ... & ... & ... & ... \\\\ \n{\\bfseries Sum} & {\\bfseries 935.300} & {\\bfseries 410.700} & {\\bfseries 935.300} & {\\bfseries 3.553 $\\times$ 10\\textsuperscript{-14}} & {\\bfseries 2,821.586} \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}}\\(\\hat B = \\sum_i y_i / \\sum_i x_i = 2.2773\\), \\(\\hat y_i = \\hat B\\, x_i\\), \\(s_e^2 = 94.0529\\).\\\\\n\\(\\hat B = \\dfrac{\\sum_i y_i}{\\sum_i x_i} = \\dfrac{935.300}{410.700} = 2.277\\)\\\\\n\\(\\mathrm{SE}(\\hat B) = \\dfrac{1}{\\bar x}\\sqrt{\\left(1-\\dfrac{n}{N}\\right)\\dfrac{s_e^2}{n}} = \\dfrac{1}{13.248}\\sqrt{\\left(1-\\dfrac{31}{2967}\\right)\\dfrac{94.053}{31}} = 0.131\\)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nplot(cherry$volume ~ cherry$diameter, main=\"Ratio Estimation Fit\")\nabline(a = 0, b = res_ratio_model$estimate[\"Est.\"], col=\"blue\", lwd=2)\n```\n\n::: {.cell-output-display}\n![](ratio_files/figure-pdf/cherry-ratio-est-1.pdf){fig-pos='H'}\n:::\n:::\n\n**Output Note:** The blue line represents our estimated ratio $\\hat{B} \\approx 2.28$. The working table above shows the individual residuals used to estimate $s_e^2$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB_v2d <- res_ratio_model$estimate\nB_v2d |> format_est_gt(\"ratio\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\hat{B}\\) & \\(\\mathrm{SE}(\\hat{B})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n2.2773 & 0.1308 & 2.0102 & 2.5444 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n**Output Note:** The ratio $\\hat{B}$ is estimated at 2.277 with a standard error of 0.1308.\n\n#### Estimating the mean volume of wood\n\nIf we know the true total of the population diameters is 41,835, we can derive the population mean diameter $\\overline{x}_{\\text{U}}$ and pass it as `xbarU` with `estimate = \"mean\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_diameters <- 41835 / N\nres_ratio_mean <- ratio_est(ydata, xdata, xbarU = mean_diameters, N = N, estimate = \"mean\")\nres_ratio_mean$table\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Ratio Estimation: Working Table\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  \\(n = 31\\)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}p{\\dimexpr 30.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}}\n\\toprule\n\\(i\\) & \\(y_i\\) & \\(x_i\\) & \\(\\hat y_i\\)\\textsuperscript{\\textit{1}} & \\(e_i\\) & \\(e_i^2\\) \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 10.300 & 8.300 & 18.902 & -8.602 & 73.992 \\\\ \n2 & 10.300 & 8.600 & 19.585 & -9.285 & 86.212 \\\\ \n3 & 10.200 & 8.800 & 20.041 & -9.841 & 96.836 \\\\ \n4 & 16.400 & 10.500 & 23.912 & -7.512 & 56.430 \\\\ \n5 & 18.800 & 10.700 & 24.367 & -5.567 & 30.996 \\\\ \n6 & 19.700 & 10.800 & 24.595 & -4.895 & 23.963 \\\\ \n... & ... & ... & ... & ... & ... \\\\ \n{\\bfseries Sum} & {\\bfseries 935.300} & {\\bfseries 410.700} & {\\bfseries 935.300} & {\\bfseries 3.553 $\\times$ 10\\textsuperscript{-14}} & {\\bfseries 2,821.586} \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}}\\(\\hat B = \\sum_i y_i / \\sum_i x_i = 2.2773\\), \\(\\hat y_i = \\hat B\\, x_i\\), \\(s_e^2 = 94.0529\\).\\\\\n\\(\\bar y_r = \\hat B\\,\\bar x_U = 2.277 \\times 14.100 = 32.111\\)\\\\\n\\(\\mathrm{SE}(\\bar y_r) = \\mathrm{SE}(\\hat B)\\,\\bar x_U = 0.131 \\times 14.100 = 1.844\\)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nratio_mean_volume_raw <- res_ratio_mean$estimate\nratio_mean_volume_raw |> format_est_gt(\"ratio_mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\bar{y}_{r}\\) & \\(\\mathrm{SE}(\\bar{y}_{r})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n32.1106 & 1.8441 & 28.3445 & 35.8768 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n#### Estimating the total volume of wood\n\nUsing `estimate = \"total\"` with the known population total diameter gives the estimated population total volume directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_diameters <- 41835\n\nres_ratio_total <- ratio_est(ydata, xdata, xbarU = t_diameters / N, N = N, estimate = \"total\")\nres_ratio_total$table\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Ratio Estimation: Working Table\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  \\(n = 31\\)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}p{\\dimexpr 30.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}}\n\\toprule\n\\(i\\) & \\(y_i\\) & \\(x_i\\) & \\(\\hat y_i\\)\\textsuperscript{\\textit{1}} & \\(e_i\\) & \\(e_i^2\\) \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 10.300 & 8.300 & 18.902 & -8.602 & 73.992 \\\\ \n2 & 10.300 & 8.600 & 19.585 & -9.285 & 86.212 \\\\ \n3 & 10.200 & 8.800 & 20.041 & -9.841 & 96.836 \\\\ \n4 & 16.400 & 10.500 & 23.912 & -7.512 & 56.430 \\\\ \n5 & 18.800 & 10.700 & 24.367 & -5.567 & 30.996 \\\\ \n6 & 19.700 & 10.800 & 24.595 & -4.895 & 23.963 \\\\ \n... & ... & ... & ... & ... & ... \\\\ \n{\\bfseries Sum} & {\\bfseries 935.300} & {\\bfseries 410.700} & {\\bfseries 935.300} & {\\bfseries 3.553 $\\times$ 10\\textsuperscript{-14}} & {\\bfseries 2,821.586} \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}}\\(\\hat B = \\sum_i y_i / \\sum_i x_i = 2.2773\\), \\(\\hat y_i = \\hat B\\, x_i\\), \\(s_e^2 = 94.0529\\).\\\\\n\\(\\hat t = \\hat B\\,\\bar x_U\\,N = 2.277 \\times 14.100 \\times 2,967 = 95,272.159\\)\\\\\n\\(\\mathrm{SE}(\\hat t) = \\mathrm{SE}(\\hat B)\\,\\bar x_U\\,N = 0.131 \\times 14.100 \\times 2,967 = 5,471.434\\)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nratio_total_volume <- res_ratio_total$estimate\nratio_total_volume |> format_est_gt(\"total\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\hat{t}\\) & \\(\\mathrm{SE}(\\hat{t})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n95,272.1585 & 5,471.4344 & 84,097.9988 & 106,446.3182 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n#### Percentage of Variance Reduction\n\nHow much did ratio estimation help compared to ignoring the auxiliary variable?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvariance_reduction <- 1 - (ratio_mean_volume_raw[\"S.E.\"] / srs_mean_vol_raw[\"S.E.\"])^2\nunname(variance_reduction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6057237\n```\n\n\n:::\n:::\n\n**Output Note:** Using the diameter as an auxiliary variable reduced the variance of our estimate by 60.6% compared to simple random sampling. \n\n## Simulation study with agpop.csv\n\nLet's test this practically by drawing 2000 random samples and seeing how SRS and Ratio estimators behave under repeated sampling.\n\n### Information of population data \n\n\n::: {.cell}\n\n```{.r .cell-code}\nagpop <- read.csv(\"data/agpop.csv\")\nagpop <- agpop[agpop$acres92 != -99, ] ## remove those counties with na\n\n# sample size\nn <- 300\n# population size\nN <- nrow(agpop)\n\n# true values that we want to estimate\ntyU <- sum(agpop[, \"acres92\"])\n# suppose known for ratio estimate\ntxU <- sum(agpop[, \"acres87\"]) \nB <- tyU / txU\n\nplot(agpop[, \"acres87\"], agpop[, \"acres92\"], main=\"Acres 1992 vs Acres 1987\")\nabline(a = 0, b = B, col=\"red\")\n```\n\n::: {.cell-output-display}\n![](ratio_files/figure-pdf/agpop-load-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# linear model output\nlm_gt <- format_lm_gt(lm(agpop$acres92 ~ agpop$acres87))\nlm_gt$coef\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Coefficient Estimates\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}l|rrrr}\n\\toprule\n & Estimate & S.E. & t value & p value \\\\ \n\\midrule\\addlinespace[2.5pt]\n(Intercept) & -2,121.4881 & 864.7615 & -2.4533 & 0.0142 \\\\ \nagpop\\$acres87 & 0.9878 & 0.0016 & 607.3876 & 0.0000 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nlm_gt$fit\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Model Fit Summary\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrrr}\n\\toprule\n\\(R^2\\) & Adj. \\(R^2\\) & \\(\\hat\\sigma\\) & F-statistic & p-value \\\\ \n\\midrule\\addlinespace[2.5pt]\n0.9918 & 0.9918 & 38,562.8752 & 368,919.6409 & 0.0000 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\n# expected reduction of variance of ratio estimate to srs\nexp_var_red <- 1 - var(agpop$acres92 - B * agpop$acres87) / var(agpop$acres92)\nexp_var_red\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9917355\n```\n\n\n:::\n:::\n\n**Output Note:** Past acreage (1987) strongly predicts current acreage (1992). The theoretically expected variance reduction is roughly 99.2%.\n\n### Simulation Studies\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnsim <- 2000\nsim_rat <- data.frame(simple = rep(0, nsim), ratio = rep(0, nsim), B = rep(0, nsim))\n\nfor (i in 1:nsim) {\n  srs <- sample(N, n)\n  y_srs <- agpop[srs, \"acres92\"]\n  x_srs <- agpop[srs, \"acres87\"]\n\n  # SRS estimate (Total)\n  sim_rat$simple[i] <- mean(y_srs) * N \n  # ratio estimate (Total)\n  sim_rat$B[i] <- mean(y_srs) / mean(x_srs)\n  sim_rat$ratio[i] <-  sim_rat$B[i] * txU\n}\n\nboxplot(sim_rat[, 1:2], main=\"Estimator Variance: SRS vs Ratio\")\nabline(h = tyU, col = \"red\", lwd=2)\n```\n\n::: {.cell-output-display}\n![](ratio_files/figure-pdf/agpop-simulation-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nWe now calculate the actual variance across our 2000 simulations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_var <- sapply(sim_rat[, 1:2], var)\nratio_sim_var <- sim_var / sim_var[1]\npercentage_reduction <- 1 - ratio_sim_var\n\ndata.frame(sim_var, ratio_sim_var, percentage_reduction) |> \n  gt(rownames_to_stub = TRUE) |> \n  cols_label(\n    sim_var = \"Variance\",\n    ratio_sim_var = \"Relative Variance\",\n    percentage_reduction = \"Variance Reduction\"\n  ) |>\n  fmt_number(columns = c(sim_var), decimals = 0) |> \n  fmt_percent(columns = c(percentage_reduction), decimals = 2) |>\n  fmt_number(columns = c(ratio_sim_var), decimals = 4)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}l|rrr}\n\\toprule\n & Variance & Relative Variance & Variance Reduction \\\\ \n\\midrule\\addlinespace[2.5pt]\nsimple & 5,213,314,477,201,806 & 1.0000 & 0.00\\% \\\\ \nratio & 41,402,676,537,526 & 0.0079 & 99.21\\% \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n**Output Note:** The boxplot dramatically illustrates the precision gain. The variance of the ratio estimator is only 0.8% of the SRS variance, confirming our theoretical expectations.\n\n## Estimating Domain Means and Post-stratification with agsrs.csv example\n\n### Estimating Domain Means\n\nWhen estimating the mean for a specific subgroup (like a region), the sample size in that subgroup ($n_d$) is a random variable, which increases our uncertainty.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagsrs <- read.csv(\"data/agsrs.csv\")\nn <- nrow(agsrs)\n\n## estimating domain means\nregion_agsrs_domain <- data.frame(rbind(\n    NC = domain_est(agsrs$acres92[agsrs$region==\"NC\"], n=n, N = 3078),\n    NE = domain_est(agsrs$acres92[agsrs$region==\"NE\"], n=n, N = 3078),\n    S  = domain_est(agsrs$acres92[agsrs$region==\"S\"], n=n, N = 3078),\n    W  = domain_est(agsrs$acres92[agsrs$region==\"W\"], n=n, N = 3078)\n))\n\nregion_agsrs_domain |> format_est_gt(\"domain_mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}l|rrrr}\n\\toprule\n & \\(\\bar{y}_{d}\\) & \\(\\mathrm{SE}(\\bar{y}_{d})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\nNC & 323,416.4359 & 30,008.3469 & 263,662.1833 & 383,170.6885 \\\\ \nNE & 106,549.0000 & 28,957.5582 & 45,453.8926 & 167,644.1074 \\\\ \nS & 246,185.8375 & 23,503.6178 & 199,766.2813 & 292,605.3937 \\\\ \nW & 518,977.6364 & 70,298.6900 & 377,206.8165 & 660,748.4562 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nIf we incorrectly used the standard SRS formula (pretending $n_d$ was fixed), our standard errors would be artificially low:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## naively applying SRS estimation to each domain (incorrect analysis)\nregion_agsrs_srs <- data.frame(rbind(\n    NC = srs_est(agsrs$acres92[agsrs$region==\"NC\"], N = 1054, estimate = \"mean\", show.details = FALSE)$estimate,\n    NE = srs_est(agsrs$acres92[agsrs$region==\"NE\"], N = 220,  estimate = \"mean\", show.details = FALSE)$estimate,\n    S  = srs_est(agsrs$acres92[agsrs$region==\"S\"],  N = 1382, estimate = \"mean\", show.details = FALSE)$estimate,\n    W  = srs_est(agsrs$acres92[agsrs$region==\"W\"],  N = 422,  estimate = \"mean\", show.details = FALSE)$estimate\n))\n\nregion_agsrs_srs |> format_est_gt(\"mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}l|rrrr}\n\\toprule\n & \\(\\bar{y}\\) & \\(\\mathrm{SE}(\\bar{y})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\nNC & 323,416.4359 & 30,395.8898 & 262,890.4867 & 383,942.3851 \\\\ \nNE & 106,549.0000 & 29,207.5056 & 44,926.5496 & 168,171.4504 \\\\ \nS & 246,185.8375 & 23,264.0052 & 200,239.5154 & 292,132.1596 \\\\ \nW & 518,977.6364 & 70,033.3811 & 377,741.8630 & 660,213.4097 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n**Output Note:** Comparing the two tables, you can see the correct `domain_mean` Standard Errors are larger, appropriately penalizing us for the uncertainty in how many counties from each region randomly fell into our sample.\n\n### Post-stratification Analysis\n\nIf we know the true regional population sizes ($N_h$), we can post-stratify our SRS data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnh <- tapply(agsrs[, \"acres92\"], agsrs[,\"region\"], length)\nn <- sum(nh)\nsh <- tapply(agsrs[, \"acres92\"], agsrs[,\"region\"], sd)\nybarh <- tapply(agsrs[, \"acres92\"], agsrs[,\"region\"], mean)\n# create a vector with external information\nNh <- c(NC = 1054, NE = 220, S = 1382, W = 422)\n```\n:::\n\n\n**Create $n_h^{\\text{post-strat}} = n \\times \\frac{N_h}{N}$**, instead of using the randomly observed $n_h$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnh_post <- Nh / sum(Nh) * n\n\n## regional summary for stratified sampling estimation\ndata.frame(\n  ybarh = ybarh, \n  sh = sh, \n  nh = nh, \n  pi_obs = nh/n, \n  Nh = Nh, \n  pi_pop = Nh/sum(Nh),  \n  nh_post = nh_post\n) |> \n  gt(rownames_to_stub = TRUE) |>\n  cols_label(\n    ybarh = md(\"$\\\\bar{y}_h$\"),\n    sh = md(\"$s_h$\"),\n    nh = md(\"$n_h^{\\\\text{obs}}$\"),\n    pi_obs = md(\"$\\\\pi^{\\\\text{obs}}_h$\"),\n    Nh = md(\"$N_h$\"),\n    pi_pop = md(\"$\\\\pi^{\\\\text{pop}}_h$\"),\n    nh_post = md(\"$n_h^{\\\\text{post}}$\")\n  ) |> \n  fmt_number(columns = c(ybarh, sh, pi_obs, pi_pop, nh_post), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}l|rrrrrrr}\n\\toprule\n & \\(\\bar{y}_h\\) & \\(s_h\\) & \\(n_h^{\\text{obs}}\\) & \\(\\pi^{\\text{obs}}_h\\) & \\(N_h\\) & \\(\\pi^{\\text{pop}}_h\\) & \\(n_h^{\\text{post}}\\) \\\\ \n\\midrule\\addlinespace[2.5pt]\nNC & 323,416.436 & 278,970.037 & 78 & 0.260 & 1054 & 0.342 & 102.729 \\\\ \nNE & 106,549.000 & 129,320.203 & 18 & 0.060 & 220 & 0.071 & 21.442 \\\\ \nS & 246,185.837 & 312,941.310 & 160 & 0.533 & 1382 & 0.449 & 134.698 \\\\ \nW & 518,977.636 & 490,842.046 & 44 & 0.147 & 422 & 0.137 & 41.131 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n**Output Note:** The table above shows the difference between the sample proportion ($\\pi^{obs}_h$) and the true population proportion ($\\pi^{pop}_h$). Post-stratification forces the weights to reflect the true population structure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## strata mean estimate\nres_post_strat <- str_est(ybarh, sh, nh_post, Nh, estimate = \"mean\")\nres_post_strat$table\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Stratified Mean Estimation: Working Table\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}p{\\dimexpr 82.50pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 45.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 45.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 82.50pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 82.50pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 82.50pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 82.50pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 82.50pt -2\\tabcolsep-1.5\\arrayrulewidth}}\n\\toprule\nStratum & \\(N_h\\) & \\(n_h\\) & \\(\\pi_h\\)\\textsuperscript{\\textit{1}} & \\(\\bar y_h\\) & \\(s_h^2\\) & \\(\\pi_h\\bar y_h\\) & \\(v_h\\)\\textsuperscript{\\textit{2}} \\\\ \n\\midrule\\addlinespace[2.5pt]\nNC & 1,054 & 103 & 0.34 & 3.23 $\\times$ 10\\textsuperscript{5} & 7.78 $\\times$ 10\\textsuperscript{10} & 1.11 $\\times$ 10\\textsuperscript{5} & 8.02 $\\times$ 10\\textsuperscript{7} \\\\ \nNE & 220 & 21 & 0.07 & 1.07 $\\times$ 10\\textsuperscript{5} & 1.67 $\\times$ 10\\textsuperscript{10} & 7.62 $\\times$ 10\\textsuperscript{3} & 3.60 $\\times$ 10\\textsuperscript{6} \\\\ \nS & 1,382 & 135 & 0.45 & 2.46 $\\times$ 10\\textsuperscript{5} & 9.79 $\\times$ 10\\textsuperscript{10} & 1.11 $\\times$ 10\\textsuperscript{5} & 1.32 $\\times$ 10\\textsuperscript{8} \\\\ \nW & 422 & 41 & 0.14 & 5.19 $\\times$ 10\\textsuperscript{5} & 2.41 $\\times$ 10\\textsuperscript{11} & 7.12 $\\times$ 10\\textsuperscript{4} & 9.94 $\\times$ 10\\textsuperscript{7} \\\\ \n{\\bfseries Total} & {\\bfseries 3,078} & {\\bfseries 300} & {\\bfseries 1.00} & {\\bfseries } & {\\bfseries } & {\\bfseries 3.00 $\\times$ 10\\textsuperscript{5}} & {\\bfseries 3.15 $\\times$ 10\\textsuperscript{8}} \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}}\\(\\pi_h = N_h/N\\) is the stratum weight.\\\\\n\\textsuperscript{\\textit{2}}\\(v_h = (1-n_h/N_h)\\,\\pi_h^2\\, s_h^2/n_h\\) is stratum \\(h\\)'s contribution to \\(V(\\bar y_{str}) = \\sum_h v_h\\).\\\\\n\\(\\bar y_{str} = \\sum_h \\pi_h\\bar y_h = 3.001 \\times 10^{5}\\)\\\\\n\\(\\mathrm{SE}(\\bar y_{str}) = \\sqrt{\\sum_h v_h} = \\sqrt{3.154 \\times 10^{8}} = 17,760.257\\)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\npost_strat_est <- res_post_strat$estimate\npost_strat_est |> format_est_gt(\"mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\bar{y}\\) & \\(\\mathrm{SE}(\\bar{y})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n300,051.6873 & 17,760.2566 & 265,241.5844 & 334,861.7901 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\n## compare with SRS estimate\nres_srs_est <- srs_est(agsrs$acres92, N = 3087, estimate = \"mean\", show.details = FALSE)\nsrs_est_raw <- res_srs_est$estimate\nsrs_est_raw |> format_est_gt(\"mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\bar{y}\\) & \\(\\mathrm{SE}(\\bar{y})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n297,897.0467 & 18,901.4092 & 260,700.4027 & 335,093.6907 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\n## true mean check\nmean(agpop$acres92)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 308582.4\n```\n\n\n:::\n:::\n\n**Output Note:** The post-stratified estimate gives a Standard Error of \\ensuremath{1.77603\\times 10^{4}}, which is more precise than the unadjusted SRS standard error of \\ensuremath{1.89014\\times 10^{4}}.\n\n## Estimating Domain Means and Post-stratification with teacher example\n\n### Importing Data and Calculating Contingency Table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nteacher <- read.csv(\"data/college_teacher.csv\")\n\ntable(teacher[, 2:1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      teacher\ngender   0   1\n     1 156  84\n     2 120  40\n```\n\n\n:::\n\n```{.r .cell-code}\naddmargins(table(teacher[, 2:1]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      teacher\ngender   0   1 Sum\n     1 156  84 240\n     2 120  40 160\n```\n\n\n:::\n\n```{.r .cell-code}\n# Proportions of students who want to become a teacher in two domains (female and male)\nprop.table(table(teacher[, 2:1]), margin = \"gender\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      teacher\ngender    0    1\n     1 0.65 0.35\n     2 0.75 0.25\n```\n\n\n:::\n:::\n\n\n### Domain Summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- nrow(teacher)\nybarh <- tapply(teacher$teacher, INDEX = teacher$gender, FUN = mean)\nsh <- tapply(teacher$teacher, INDEX = teacher$gender, FUN = sd)\nnh <- tapply(teacher$teacher, INDEX = teacher$gender, FUN = length)\nprop_h_obs <- nh / sum(nh)\n\ndata.frame(\n  ybarh = ybarh, \n  sh = sh, \n  nh = nh, \n  pi_obs = prop_h_obs\n) |> \n  gt(rownames_to_stub = TRUE) |>\n  cols_label(\n    ybarh = md(\"$\\\\bar{y}_h$\"),\n    sh = md(\"$s_h$\"),\n    nh = md(\"$n^{\\\\text{obs}}_h$\"),\n    pi_obs = md(\"$\\\\pi^{\\\\text{obs}}_h$\")\n  ) |> \n  fmt_number(columns = everything(), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}l|rrrr}\n\\toprule\n & \\(\\bar{y}_h\\) & \\(s_h\\) & \\(n^{\\text{obs}}_h\\) & \\(\\pi^{\\text{obs}}_h\\) \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 0.350 & 0.478 & 240.000 & 0.600 \\\\ \n2 & 0.250 & 0.434 & 160.000 & 0.400 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n### Estimating Domain Means\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNh <- c(3000, 1000)\nn <- nrow(teacher)\ndomain_teacher_est <- data.frame(rbind(\n    female = domain_est(subset(teacher, gender==1)$teacher, n=n, N=4000),\n    male   = domain_est(subset(teacher, gender==2)$teacher, n=n, N=4000)\n))\n\ndomain_teacher_est |> format_est_gt(\"domain_mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}l|rrrr}\n\\toprule\n & \\(\\bar{y}_{d}\\) & \\(\\mathrm{SE}(\\bar{y}_{d})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\nfemale & 0.3500 & 0.0293 & 0.2923 & 0.4077 \\\\ \nmale & 0.2500 & 0.0326 & 0.1857 & 0.3143 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n### Post-stratification Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNh <- c(3000, 1000)\nprop_h_pop <- Nh / sum(Nh)\nprop_h_pop\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.75 0.25\n```\n\n\n:::\n:::\n\n#### Create $n_h^{\\text{post-strat}} = n \\times \\frac{N_h}{N}$ {-}\n\n::: {.cell}\n\n```{.r .cell-code}\nnh_post <- Nh / sum(Nh) * n\n\n## show the differences\ndata.frame(\n  phat = ybarh, \n  sh = sh, \n  nh = nh, \n  pi_obs = nh/n, \n  Nh = Nh, \n  pi_pop = Nh/sum(Nh),  \n  nh_post = nh_post\n) |> \n  gt(rownames_to_stub = TRUE) |> \n  cols_label(\n    phat = md(\"$\\\\hat{p}_h$\"),\n    sh = md(\"$s_h$\"),\n    nh = md(\"$n_h$\"),\n    pi_obs = md(\"$\\\\pi^{\\\\text{obs}}_h$\"),\n    Nh = md(\"$N_h$\"),\n    pi_pop = md(\"$\\\\pi^{\\\\text{pop}}_h$\"),\n    nh_post = md(\"$n_h^{\\\\text{post-strat}}$\")\n  ) |> \n  fmt_number(columns = c(phat, sh, pi_obs, pi_pop, nh_post), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}l|rrrrrrr}\n\\toprule\n & \\(\\hat{p}_h\\) & \\(s_h\\) & \\(n_h\\) & \\(\\pi^{\\text{obs}}_h\\) & \\(N_h\\) & \\(\\pi^{\\text{pop}}_h\\) & \\(n_h^{\\text{post-strat}}\\) \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 0.350 & 0.478 & 240 & 0.600 & 3000 & 0.750 & 300.000 \\\\ \n2 & 0.250 & 0.434 & 160 & 0.400 & 1000 & 0.250 & 100.000 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nCalculate the post-stratification estimation of the mean:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## poststratification estimation of mean\nres_teacher_post_strat <- str_est(ybarh, sh, nh_post, Nh, estimate = \"mean\")\nres_teacher_post_strat$table\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Stratified Mean Estimation: Working Table\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}p{\\dimexpr 82.50pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 45.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 45.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 82.50pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 82.50pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 82.50pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 82.50pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 82.50pt -2\\tabcolsep-1.5\\arrayrulewidth}}\n\\toprule\nStratum & \\(N_h\\) & \\(n_h\\) & \\(\\pi_h\\)\\textsuperscript{\\textit{1}} & \\(\\bar y_h\\) & \\(s_h^2\\) & \\(\\pi_h\\bar y_h\\) & \\(v_h\\)\\textsuperscript{\\textit{2}} \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 3,000 & 300 & 0.75 & 0.35 & 0.23 & 0.26 & 3.86 $\\times$ 10\\textsuperscript{-4} \\\\ \n2 & 1,000 & 100 & 0.25 & 0.25 & 0.19 & 0.06 & 1.06 $\\times$ 10\\textsuperscript{-4} \\\\ \n{\\bfseries Total} & {\\bfseries 4,000} & {\\bfseries 400} & {\\bfseries 1.00} & {\\bfseries } & {\\bfseries } & {\\bfseries 0.32} & {\\bfseries 4.92 $\\times$ 10\\textsuperscript{-4}} \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}}\\(\\pi_h = N_h/N\\) is the stratum weight.\\\\\n\\textsuperscript{\\textit{2}}\\(v_h = (1-n_h/N_h)\\,\\pi_h^2\\, s_h^2/n_h\\) is stratum \\(h\\)'s contribution to \\(V(\\bar y_{str}) = \\sum_h v_h\\).\\\\\n\\(\\bar y_{str} = \\sum_h \\pi_h\\bar y_h = 0.325\\)\\\\\n\\(\\mathrm{SE}(\\bar y_{str}) = \\sqrt{\\sum_h v_h} = \\sqrt{4.916 \\times 10^{-4}} = 0.022\\)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nteacher_post_strat <- res_teacher_post_strat$estimate\nteacher_post_strat |> format_est_gt(\"mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\bar{y}\\) & \\(\\mathrm{SE}(\\bar{y})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n0.3250 & 0.0222 & 0.2815 & 0.3685 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nThis post-stratification estimate explicitly corrects for the sampling imbalance using the true strata sizes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 0.35 * 0.75 + 0.25 * 0.25 \n(ybarh[1] * prop_h_pop[1]) + (ybarh[2] * prop_h_pop[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    1 \n0.325 \n```\n\n\n:::\n:::\n\n\n### Comparing to the Analysis with SRS\n\nIf we didn't post-stratify, the simple mean is heavily weighted toward males because they were over-sampled by chance (40% in sample vs 25% in population).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_teacher_srs <- srs_est(teacher$teacher, N=sum(Nh), estimate = \"mean\", show.details = FALSE)\nres_teacher_srs$table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n\n```{.r .cell-code}\nteacher_srs <- res_teacher_srs$estimate\nteacher_srs |> format_est_gt(\"mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\bar{y}\\) & \\(\\mathrm{SE}(\\bar{y})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n0.3100 & 0.0220 & 0.2668 & 0.3532 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nThis equals the naive sample proportion:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 0.35 * 0.6 + 0.25 * 0.4\nmean(teacher$teacher == 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.31\n```\n\n\n:::\n:::\n\n\n## Regression Estimation for the cherry.csv dataset \n\nWhen the relationship between $y$ and $x$ doesn't pass exactly through the origin, we use Regression Estimation.\n\n### Importing data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncherry <- read.csv(\"data/cherry.csv\", header = T)\nydata <- cherry$volume \nxdata <- cherry$diameter\nt_diameters <- 41835\nxbarU <- t_diameters / 2967 \nN <- 2967\n```\n:::\n\n\n### Regression Estimation Using the Function\n\n#### Fitting a linear regression model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(ydata)\nlmfit <- lm(ydata ~ xdata)\nlmfit_gt <- format_lm_gt(lmfit)\nlmfit_gt$coef\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Coefficient Estimates\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}l|rrrr}\n\\toprule\n & Estimate & S.E. & t value & p value \\\\ \n\\midrule\\addlinespace[2.5pt]\n(Intercept) & -36.9435 & 3.3651 & -10.9783 & 0.0000 \\\\ \nxdata & 5.0659 & 0.2474 & 20.4783 & 0.0000 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nlmfit_gt$fit\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Model Fit Summary\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrrr}\n\\toprule\n\\(R^2\\) & Adj. \\(R^2\\) & \\(\\hat\\sigma\\) & F-statistic & p-value \\\\ \n\\midrule\\addlinespace[2.5pt]\n0.9353 & 0.9331 & 4.2520 & 419.3603 & 0.0000 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nplot(xdata, ydata, main=\"Linear Regression: Volume vs Diameter\")\nabline(lmfit, col=\"green\", lwd=2)\n```\n\n::: {.cell-output-display}\n![](ratio_files/figure-pdf/cherry-reg-fit-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe function's `$table` shows the row-level working values $x_i$, $y_i$, fitted $\\hat{y}_i = \\hat{B}_0 + \\hat{B}_1 x_i$, residuals $e_i = y_i - \\hat{y}_i$, and $e_i^2$ (with a Sum row and a footnote giving $\\hat B_0$, $\\hat B_1$, and $s_e^2$):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_reg_model <- reg_est(ydata, xdata, N = N, estimate = \"model\")\nres_reg_model$table\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Regression Estimation: Working Table\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  \\(n = 31\\)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}p{\\dimexpr 30.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}}\n\\toprule\n\\(i\\) & \\(y_i\\) & \\(x_i\\) & \\(\\hat y_i\\)\\textsuperscript{\\textit{1}} & \\(e_i\\) & \\(e_i^2\\) \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 10.300 & 8.300 & 5.103 & 5.197 & 27.007 \\\\ \n2 & 10.300 & 8.600 & 6.623 & 3.677 & 13.521 \\\\ \n3 & 10.200 & 8.800 & 7.636 & 2.564 & 6.574 \\\\ \n4 & 16.400 & 10.500 & 16.248 & 1.520 $\\times$ 10\\textsuperscript{-1} & 0.023 \\\\ \n5 & 18.800 & 10.700 & 17.261 & 1.539 & 2.368 \\\\ \n6 & 19.700 & 10.800 & 17.768 & 1.932 & 3.733 \\\\ \n... & ... & ... & ... & ... & ... \\\\ \n{\\bfseries Sum} & {\\bfseries 935.300} & {\\bfseries 410.700} & {\\bfseries 935.300} & {\\bfseries -3.553 $\\times$ 10\\textsuperscript{-15}} & {\\bfseries 524.303} \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}}\\(\\hat B_0 = -36.9435\\), \\(\\hat B_1 = 5.0659\\), \\(\\hat y_i = \\hat B_0 + \\hat B_1 x_i\\), \\(s_e^2 = 18.0794\\).\\\\\n\\(\\hat B_1 = \\dfrac{\\sum_i(x_i-\\bar x)(y_i-\\bar y)}{\\sum_i(x_i-\\bar x)^2} = \\dfrac{1,496.644}{295.437} = 5.066\\)\\\\\n\\(\\mathrm{SE}(\\hat B_1) = \\sqrt{\\dfrac{s_e^2}{\\sum_i(x_i-\\bar x)^2}} = \\sqrt{\\dfrac{18.079}{295.437}} = 0.247\\)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n:::\n\n\n#### Estimate the mean\n\nWe compute the regression estimate $\\overline{y}_{reg}$ by passing `xbarU` with `estimate = \"mean\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_reg_mean <- reg_est(ydata, xdata, xbarU = xbarU, N = N, estimate = \"mean\")\nres_reg_mean$table\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Regression Estimation: Working Table\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  \\(n = 31\\)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}p{\\dimexpr 30.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}}\n\\toprule\n\\(i\\) & \\(y_i\\) & \\(x_i\\) & \\(\\hat y_i\\)\\textsuperscript{\\textit{1}} & \\(e_i\\) & \\(e_i^2\\) \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 10.300 & 8.300 & 5.103 & 5.197 & 27.007 \\\\ \n2 & 10.300 & 8.600 & 6.623 & 3.677 & 13.521 \\\\ \n3 & 10.200 & 8.800 & 7.636 & 2.564 & 6.574 \\\\ \n4 & 16.400 & 10.500 & 16.248 & 1.520 $\\times$ 10\\textsuperscript{-1} & 0.023 \\\\ \n5 & 18.800 & 10.700 & 17.261 & 1.539 & 2.368 \\\\ \n6 & 19.700 & 10.800 & 17.768 & 1.932 & 3.733 \\\\ \n... & ... & ... & ... & ... & ... \\\\ \n{\\bfseries Sum} & {\\bfseries 935.300} & {\\bfseries 410.700} & {\\bfseries 935.300} & {\\bfseries -3.553 $\\times$ 10\\textsuperscript{-15}} & {\\bfseries 524.303} \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}}\\(\\hat B_0 = -36.9435\\), \\(\\hat B_1 = 5.0659\\), \\(\\hat y_i = \\hat B_0 + \\hat B_1 x_i\\), \\(s_e^2 = 18.0794\\).\\\\\n\\(\\bar y_{reg} = \\hat B_0+\\hat B_1\\bar x_U = -36.943 + 5.066 \\times 14.100 = 34.486\\)\\\\\n\\(\\mathrm{SE}(\\bar y_{reg}) = \\sqrt{\\left(1-\\dfrac{n}{N}\\right)\\dfrac{s_e^2}{n}} = \\sqrt{\\left(1-\\dfrac{31}{2967}\\right)\\dfrac{18.079}{31}} = 0.760\\)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\noutput_reg <- res_reg_mean$estimate\noutput_reg |> format_est_gt(\"reg_mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\bar{y}_{reg}\\) & \\(\\mathrm{SE}(\\bar{y}_{reg})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n34.4856 & 0.7597 & 32.9319 & 36.0393 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n**Output Note:** The Regression estimate for the mean volume is 34.486 with a standard error of 0.7597.\n\n#### Estimate the total\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg_total_volume_raw <- reg_est(ydata, xdata, xbarU = xbarU, N = N, estimate = \"total\")$estimate\nreg_total_volume_raw |> format_est_gt(\"reg_total\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\hat{t}_{reg}\\) & \\(\\mathrm{SE}(\\hat{t}_{reg})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n102,318.8602 & 2,253.9690 & 97,708.9761 & 106,928.7444 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n#### Percentage of Variance Reduction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg_mean_volume_raw <- output_reg\nvar_reduction_reg <- 1 - (reg_mean_volume_raw[\"S.E.\"] / srs_mean_vol_raw[\"S.E.\"])^2\nunname(var_reduction_reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9330895\n```\n\n\n:::\n:::\n\n**Output Note:** The variance reduction for the regression estimator is 93.3%, which is similar to the ratio estimator since the true intercept is very close to zero.\n\n## Regression estimation for photo counts of dead trees\n\nTo estimate the number of dead trees in an area, we divide the area into 100 square plots and count dead trees on photographs. We select an SRS of 25 plots for exact field counts. We know the true mean photo count is 11.3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphotocounts <- c(10, 12, 7, 13, 13, 6, 17, 16, 15, 10, 14, 12, 10, 5, 12, 10,\n                 10, 9, 6, 11, 7, 9, 11, 10, 10)\n\nfieldcounts <- c(15, 14, 9, 14, 8, 5, 18, 15, 13, 15, 11, 15, 12, 8, 13,\n                 9, 11, 12, 9, 12, 13, 11, 10, 9, 8)\n\nlmfit <- lm(fieldcounts ~ photocounts)\nlmfit_gt <- format_lm_gt(lmfit)\nlmfit_gt$coef\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Coefficient Estimates\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}l|rrrr}\n\\toprule\n & Estimate & S.E. & t value & p value \\\\ \n\\midrule\\addlinespace[2.5pt]\n(Intercept) & 5.0593 & 1.7635 & 2.8689 & 0.0087 \\\\ \nphotocounts & 0.6133 & 0.1601 & 3.8316 & 0.0009 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nlmfit_gt$fit\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Model Fit Summary\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrrr}\n\\toprule\n\\(R^2\\) & Adj. \\(R^2\\) & \\(\\hat\\sigma\\) & F-statistic & p-value \\\\ \n\\midrule\\addlinespace[2.5pt]\n0.3896 & 0.3631 & 2.4062 & 14.6815 & 0.0009 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nplot(photocounts, fieldcounts, main=\"Field Counts vs Photo Counts\")\nabline(lmfit, col=\"purple\", lwd=2)\n```\n\n::: {.cell-output-display}\n![](ratio_files/figure-pdf/deadtrees-data-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nLet's compare the three different estimation methods to see which provides the lowest Standard Error for the population mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Regression estimate for the mean\nres_dt_reg <- reg_est(ydata = fieldcounts, xdata = photocounts, xbarU = 11.3, N = 100, estimate = \"mean\")\nres_dt_reg$table\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Regression Estimation: Working Table\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  \\(n = 25\\)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}p{\\dimexpr 30.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}}\n\\toprule\n\\(i\\) & \\(y_i\\) & \\(x_i\\) & \\(\\hat y_i\\)\\textsuperscript{\\textit{1}} & \\(e_i\\) & \\(e_i^2\\) \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 15.000 & 10.000 & 11.192 & 3.808 & 14.501 \\\\ \n2 & 14.000 & 12.000 & 12.419 & 1.581 & 2.501 \\\\ \n3 & 9.000 & 7.000 & 9.352 & -3.522 $\\times$ 10\\textsuperscript{-1} & 0.124 \\\\ \n4 & 14.000 & 13.000 & 13.032 & 9.681 $\\times$ 10\\textsuperscript{-1} & 0.937 \\\\ \n5 & 8.000 & 13.000 & 13.032 & -5.032 & 25.320 \\\\ \n6 & 5.000 & 6.000 & 8.739 & -3.739 & 13.980 \\\\ \n... & ... & ... & ... & ... & ... \\\\ \n{\\bfseries Sum} & {\\bfseries 289.000} & {\\bfseries 265.000} & {\\bfseries 289.000} & {\\bfseries -2.665 $\\times$ 10\\textsuperscript{-15}} & {\\bfseries 133.160} \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}}\\(\\hat B_0 = 5.0593\\), \\(\\hat B_1 = 0.6133\\), \\(\\hat y_i = \\hat B_0 + \\hat B_1 x_i\\), \\(s_e^2 = 5.7896\\).\\\\\n\\(\\bar y_{reg} = \\hat B_0+\\hat B_1\\bar x_U = 5.059 + 0.613 \\times 11.300 = 11.989\\)\\\\\n\\(\\mathrm{SE}(\\bar y_{reg}) = \\sqrt{\\left(1-\\dfrac{n}{N}\\right)\\dfrac{s_e^2}{n}} = \\sqrt{\\left(1-\\dfrac{25}{100}\\right)\\dfrac{5.790}{25}} = 0.417\\)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\ndt_reg_raw <- res_dt_reg$estimate\ndt_reg_raw |> format_est_gt(\"reg_mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\bar{y}_{reg}\\) & \\(\\mathrm{SE}(\\bar{y}_{reg})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n11.9893 & 0.4168 & 11.1272 & 12.8514 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\n# (And estimating the total)\nreg_est(ydata = fieldcounts, xdata = photocounts, xbarU = 11.3, N = 100, estimate = \"total\")$estimate |>\n  format_est_gt(\"reg_total\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\hat{t}_{reg}\\) & \\(\\mathrm{SE}(\\hat{t}_{reg})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n1,198.9292 & 41.6758 & 1,112.7163 & 1,285.1422 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\n# 2. Simple random sampling estimate for the mean (Ignoring photo counts)\nres_dt_srs <- srs_est(sdata = fieldcounts, N = 100, estimate = \"mean\", show.details = FALSE)\ndt_srs_raw <- res_dt_srs$estimate\ndt_srs_raw |> format_est_gt(\"mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\bar{y}\\) & \\(\\mathrm{SE}(\\bar{y})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n11.5600 & 0.5222 & 10.4822 & 12.6378 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\n# 3. Ratio estimate for the mean\nres_dt_ratio <- ratio_est(ydata = fieldcounts, xdata = photocounts, xbarU = 11.3, N = 100, estimate = \"mean\")\nres_dt_ratio$table\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Ratio Estimation: Working Table\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  \\(n = 25\\)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}p{\\dimexpr 30.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}}\n\\toprule\n\\(i\\) & \\(y_i\\) & \\(x_i\\) & \\(\\hat y_i\\)\\textsuperscript{\\textit{1}} & \\(e_i\\) & \\(e_i^2\\) \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 15.000 & 10.000 & 10.906 & 4.094 & 16.764 \\\\ \n2 & 14.000 & 12.000 & 13.087 & 9.132 $\\times$ 10\\textsuperscript{-1} & 0.834 \\\\ \n3 & 9.000 & 7.000 & 7.634 & 1.366 & 1.866 \\\\ \n4 & 14.000 & 13.000 & 14.177 & -1.774 $\\times$ 10\\textsuperscript{-1} & 0.031 \\\\ \n5 & 8.000 & 13.000 & 14.177 & -6.177 & 38.160 \\\\ \n6 & 5.000 & 6.000 & 6.543 & -1.543 & 2.382 \\\\ \n... & ... & ... & ... & ... & ... \\\\ \n{\\bfseries Sum} & {\\bfseries 289.000} & {\\bfseries 265.000} & {\\bfseries 289.000} & {\\bfseries 5.329 $\\times$ 10\\textsuperscript{-15}} & {\\bfseries 184.645} \\\\ \n\\bottomrule\n\\end{tabular*}\n\\begin{minipage}{\\linewidth}\n\\vspace{.05em}\n\\textsuperscript{\\textit{1}}\\(\\hat B = \\sum_i y_i / \\sum_i x_i = 1.0906\\), \\(\\hat y_i = \\hat B\\, x_i\\), \\(s_e^2 = 7.6935\\).\\\\\n\\(\\bar y_r = \\hat B\\,\\bar x_U = 1.091 \\times 11.300 = 12.323\\)\\\\\n\\(\\mathrm{SE}(\\bar y_r) = \\mathrm{SE}(\\hat B)\\,\\bar x_U = 0.045 \\times 11.300 = 0.512\\)\\\\\n\\end{minipage}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\ndt_ratio_raw <- res_dt_ratio$estimate\ndt_ratio_raw |> format_est_gt(\"ratio_mean\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{0.7\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\n\\(\\bar{y}_{r}\\) & \\(\\mathrm{SE}(\\bar{y}_{r})\\) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n12.3234 & 0.5121 & 11.2664 & 13.3804 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n#### Output Note: {-}\n*   **SRS Mean:** SE = 0.522\n*   **Ratio Mean:** SE = 0.512\n\n*   **Regression Mean:** SE = 0.417\n\nBecause the intercept of the true line is non-zero, the **Regression estimator** provides the most precise estimate in this scenario.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"cherry-load-plot\",\"cherry-load-plot\",\"cherry-load-plot\",\"cherry-load-plot\",\"cherry-load-plot\",\"cherry-load-plot\",\"cherry-load-plot\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-srs-est\",\"cherry-ratio-est\",\"cherry-ratio-est\",\"cherry-ratio-est\",\"cherry-ratio-est\",\"cherry-ratio-est\",\"cherry-ratio-est\",\"cherry-ratio-est\",\"cherry-ratio-b\",\"cherry-ratio-b\",\"cherry-ratio-b\",\"cherry-ratio-b\",\"cherry-ratio-b\",\"cherry-ratio-b\",\"cherry-ratio-b\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-mean\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"cherry-ratio-total\",\"agpop-load\",\"agpop-load\",\"agpop-load\",\"agpop-load\",\"agpop-load\",\"agpop-load\",\"agpop-load\",\"agpop-load\",\"agpop-load\",\"agpop-load\",\"agpop-load\",\"agpop-load\",\"agpop-load\",\"agpop-load\",\"agpop-sim-variance\",\"agpop-sim-variance\",\"agpop-sim-variance\",\"agpop-sim-variance\",\"agpop-sim-variance\",\"agpop-sim-variance\",\"agpop-sim-variance\",\"agsrs-domain-est\",\"agsrs-domain-est\",\"agsrs-domain-est\",\"agsrs-domain-est\",\"agsrs-domain-est\",\"agsrs-domain-est\",\"agsrs-domain-est\",\"agsrs-domain-srs\",\"agsrs-domain-srs\",\"agsrs-domain-srs\",\"agsrs-domain-srs\",\"agsrs-domain-srs\",\"agsrs-domain-srs\",\"agsrs-domain-srs\",\"agsrs-poststrat-table\",\"agsrs-poststrat-table\",\"agsrs-poststrat-table\",\"agsrs-poststrat-table\",\"agsrs-poststrat-table\",\"agsrs-poststrat-table\",\"agsrs-poststrat-table\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"agsrs-poststrat-est\",\"teacher-domain-summary\",\"teacher-domain-summary\",\"teacher-domain-summary\",\"teacher-domain-summary\",\"teacher-domain-summary\",\"teacher-domain-summary\",\"teacher-domain-summary\",\"teacher-domain-est\",\"teacher-domain-est\",\"teacher-domain-est\",\"teacher-domain-est\",\"teacher-domain-est\",\"teacher-domain-est\",\"teacher-domain-est\",\"teacher-poststrat-table\",\"teacher-poststrat-table\",\"teacher-poststrat-table\",\"teacher-poststrat-table\",\"teacher-poststrat-table\",\"teacher-poststrat-table\",\"teacher-poststrat-table\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-poststrat-est\",\"teacher-srs-est\",\"teacher-srs-est\",\"teacher-srs-est\",\"teacher-srs-est\",\"teacher-srs-est\",\"teacher-srs-est\",\"teacher-srs-est\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-fit\",\"cherry-reg-model\",\"cherry-reg-model\",\"cherry-reg-model\",\"cherry-reg-model\",\"cherry-reg-model\",\"cherry-reg-model\",\"cherry-reg-model\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-mean\",\"cherry-reg-total\",\"cherry-reg-total\",\"cherry-reg-total\",\"cherry-reg-total\",\"cherry-reg-total\",\"cherry-reg-total\",\"cherry-reg-total\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-data\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\",\"deadtrees-compare\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}