project:
  type: default
  output-dir: "."
  render:
    - index.qmd
    - "Lec*.qmd"
repo-url: https://github.com/longhaiSK/sampling/tree/main/sampling_slides/
format:
  html: default
  banner_slides-revealjs:
    include-after-body: back-to-all.html
date: last-modified
author: Longhai Li 
filters:
  - shinylive