project:
  type: website
  output-dir: "."

website:
  title: "Shinylive Apps for Sampling Survey"
  navbar:
    right:
      - icon: list
        aria-label: "Apps"
        menu:
          - text: "SRS"
            href: app-srs.qmd
          - text: "Stratified"
            href: app-stratified.qmd
          - text: "Ratio & regression"
            href: app-ratio.qmd
          - text: "Post-stratification"
            href: app-poststrat.qmd
          - text: "Cluster"
            href: app-cluster.qmd
          - text: "UPS"
            href: app-ups.qmd
          - text: "---"
          - text: "Back to the book"
            href: ../index.html

author:
  - name: Longhai Li
    url: https://longhaisk.github.io/
date: last-modified

format:
  html:
    theme: flatly
    page-layout: full
    toc: false
    css: shinyliveapps.css
filters:
  - shinylive
